In [2]:
import numpy as np

a = np.arange(1, 23)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22])

In [ ]:
a[0]

In [ ]:
a[-1]

In [ ]:
a[-22]

In [ ]:
b = np.random.randint(10, size = 9).reshape(3,3)
b

In [ ]:
b[-1, 2]

In [ ]:
b[-1, 0]

In [ ]:
b[-2, -3] = 9.16
b

In [32]:
c = np.arange(5, 15)
c

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [33]:
c[:3]

array([5, 6, 7])

In [34]:
c[3:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [35]:
c[3:10]

array([ 8,  9, 10, 11, 12, 13, 14])

In [36]:
c[3:9]

array([ 8,  9, 10, 11, 12, 13])

In [37]:
c

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
c[::]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [39]:
c[::2]

array([ 5,  7,  9, 11, 13])

In [40]:
c[::3]

array([ 5,  8, 11, 14])

In [41]:
c[3::3]

array([ 8, 11, 14])