In [9]:
import numpy as np
from numpy import random

a = random.randint(10, size = (3, 3, 3))
print(a)

[[[9 1 4]
  [5 3 9]
  [3 0 0]]

 [[6 7 2]
  [0 3 3]
  [2 2 4]]

 [[7 8 3]
  [7 6 7]
  [1 1 4]]]


In [12]:
b = random.randint(10000, size = (10, 10))
print(b)

print(np.max(b))
print(np.min(b))

[[9552 9348 4805 3712 8469 5954 6844 4085 3818 5627]
 [5156 3379  386 7598 5131 9523 8078 8438 7591 6811]
 [9586 7586 8694 9047 1326 2751 3161  859 4934 7188]
 [2154   19 7549 9745 7656 6300 9935 5671 9948 4403]
 [ 617 2299 8272 1344 8769 1291 1156 7594 7244 2419]
 [8789 8017 2940 3305 2036 4544 9670 7797 2853 9634]
 [5770 7530 8764 2602 6903 8667   16 9195  789 2444]
 [ 876 1712 1819 8167 6002 7010 1386 3751 1592  307]
 [2878 3866  627 5203 1696 2740 1635 1008 8696 7712]
 [9881 3159 5628 3045 2098 6053 7724 2095 6774 7582]]
9948
16


In [27]:
c = random.randint(100, size = (10))
print(c)
print(c[0::2])
print(np.mean(c, axis = 0))

[80 65 19 44 63 81 24 76 71 74]
[80 19 63 24 71]
59.7


In [39]:
d = np.ones((5, 5))
print(d)
d[1:np.shape(d)[1]-1, 1:np.shape(d)[1]-1] = 0
d

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])