In [1]:
import numpy as np

a = np.random.randint(1, 10, size=15)
a

array([4, 8, 2, 1, 4, 2, 1, 9, 6, 1, 3, 7, 6, 8, 4])

In [5]:
a[8:-10:-1]

array([6, 9, 1])

In [6]:
a[:-10]

array([4, 8, 2, 1, 4])

In [8]:
b = np.arange(15).reshape(3,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
b[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [10]:
b[1:, 1::2]

array([[ 6,  8],
       [11, 13]])

In [20]:
d = b[:, 1]
d

array([ 1,  6, 11])

In [33]:
d.shape

(3,)

In [34]:
d1 = d.reshape(-1, 1)
d1

array([[ 1],
       [ 6],
       [11]])

In [35]:
d1.shape

(3, 1)

In [22]:
e = b[:, ::-4]
e

array([[ 4,  0],
       [ 9,  5],
       [14, 10]])

In [23]:
e.shape

(3, 2)

In [14]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [18]:
c = b[::-1, -2:-4:-1]
c

array([[13, 12],
       [ 8,  7],
       [ 3,  2]])

In [31]:
c.reshape(2, -1)

array([[13, 12,  8],
       [ 7,  3,  2]])

In [36]:
f = np.arange(9).reshape(3, 3)
f

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [51]:
g = np.arange(10, 16).reshape(2, 3)
g

array([[10, 11, 12],
       [13, 14, 15]])

In [52]:
np.concatenate([f,g])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12],
       [13, 14, 15]])

In [57]:
h = np.repeat(1, 3)
h

array([1, 1, 1])

In [58]:
h.shape

(3,)

In [62]:
h.reshape(1, 3)

array([[1, 1, 1]])

In [63]:
np.concatenate([f, h.reshape(1,3)])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [1, 1, 1]])

In [44]:
np.vstack([f,g])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [65]:
np.concatenate([g, g], axis=1)

array([[10, 11, 12, 10, 11, 12],
       [13, 14, 15, 13, 14, 15]])